Jorge\GespagosBundle\Entity\Usuario:
    type: entity
    table: usuario
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: IDENTITY
        usuario:
            type: string
            length: 128
            nullable: false
        clave:
            type: string
            length: 128
            nullable: false
        nombres:
            type: string
            length: 128
            nullable: false
        apellidos:
            type: string
            length: 128
            nullable: false
        fecha:
            type: datetime
            nullable: false
        correo:
            type: string
            length: 128
            nullable: false
        salt:
            type: string
            length: 32
            nullable: false
    lifecycleCallbacks: {  }
