Jorge\GespagosBundle\Entity\Pagos:
    properties:
        nombre:
        periodo:
        constante:
        monto:
            - NotBlank: ~
        descripcion:
        actualizacion:
        creacion:
        id:
