admin_usuario:
    pattern:  /
    defaults: { _controller: "JorgeGespagosBundle:Usuario:index" }

admin_usuario_show:
    pattern:  /{id}/show
    defaults: { _controller: "JorgeGespagosBundle:Usuario:show" }

admin_usuario_new:
    pattern:  /new
    defaults: { _controller: "JorgeGespagosBundle:Usuario:new" }

admin_usuario_create:
    pattern:  /create
    defaults: { _controller: "JorgeGespagosBundle:Usuario:create" }
    requirements: { _method: post }

admin_usuario_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "JorgeGespagosBundle:Usuario:edit" }

admin_usuario_update:
    pattern:  /{id}/update
    defaults: { _controller: "JorgeGespagosBundle:Usuario:update" }
    requirements: { _method: post|put }

admin_usuario_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "JorgeGespagosBundle:Usuario:delete" }
    requirements: { _method: post|delete }
